import type { GameEvent } from '../domain/index.js';

/**
 * Banco curado de eventos. Sirve como semilla del mundo y dataset
 * de entrenamiento para la IA procedural. Cada evento tiene al menos
 * una opción "segura" (la correcta) y otras que enseñan por contraste.
 */
export const SEED_EVENTS: readonly GameEvent[] = [
  // ---------- SOCIAL MEDIA ----------
  {
    id: 'evt_social_iphone',
    zoneId: 'social_media',
    category: 'phishing',
    title: 'El mensaje dorado',
    prompt: '"¡Ganaste un iPhone 16 Pro! Reclamalo acá: bit.ly/premio-ganador"',
    context: 'Recibís un DM con un premio sospechoso.',
    speaker: { id: 'npc_influ', name: 'Max Trend', avatar: '📱', archetype: 'influencer' },
    choices: [
      {
        id: 'open',
        label: 'Abrir el link y completar el formulario',
        outcomeQuality: 'dangerous',
        deltas: { security: -25, stress: 20, money: -15, knowledge: 5 },
        feedback: 'Era phishing. Entregaste datos a un atacante.',
        teaches: 'phishing',
        xpReward: 5,
      },
      {
        id: 'ignore',
        label: 'Ignorar y bloquear al remitente',
        outcomeQuality: 'safe',
        deltas: { security: 5, knowledge: 8, stress: -5 },
        feedback: 'Bien. Los premios inesperados casi siempre son anzuelos.',
        teaches: 'phishing',
        xpReward: 30,
      },
      {
        id: 'investigate',
        label: 'Reportar como spam y verificar el usuario',
        outcomeQuality: 'educational',
        deltas: { security: 10, knowledge: 12, reputation: 5, stress: -5 },
        feedback: 'Excelente. Investigar protege a tu comunidad.',
        teaches: 'phishing',
        xpReward: 50,
      },
    ],
    minLevel: 1,
    tags: ['dm', 'premio', 'urgencia'],
    modes: ['story', 'survival', 'school'],
  },
  {
    id: 'evt_social_fakeprofile',
    zoneId: 'social_media',
    category: 'social_engineering',
    title: 'El clon perfecto',
    prompt: 'Una cuenta idéntica a la de tu amigo Joa te pide dinero urgente.',
    context: 'El perfil tiene su foto, su bio, 47 seguidores. ¿Es él?',
    speaker: { id: 'npc_amigo', name: 'Joa', avatar: '🎮', archetype: 'friend' },
    choices: [
      {
        id: 'send_money',
        label: 'Transferirle el dinero ya',
        outcomeQuality: 'dangerous',
        deltas: { money: -30, trust: -15, security: -10 },
        feedback: 'Era un perfil clonado. Tu amigo real nunca te pidió eso.',
        teaches: 'social_engineering',
        xpReward: 5,
      },
      {
        id: 'block',
        label: 'Bloquear sin más',
        outcomeQuality: 'risky',
        deltas: { security: 3, knowledge: 3 },
        feedback: 'Te protege, pero no avisas a tu amigo del clon.',
        teaches: 'social_engineering',
        xpReward: 12,
      },
      {
        id: 'call_real',
        label: 'Llamar a Joa por teléfono para confirmar',
        outcomeQuality: 'safe',
        deltas: { trust: 8, knowledge: 10, security: 6 },
        feedback: 'Verificar por otro canal es la mejor defensa.',
        teaches: 'social_engineering',
        xpReward: 35,
      },
    ],
    minLevel: 1,
    tags: ['suplantación', 'urgencia', 'dinero'],
    modes: ['story', 'survival'],
  },

  // ---------- GAMING ----------
  {
    id: 'evt_gaming_robux',
    zoneId: 'gaming',
    category: 'online_scam',
    title: 'Robux infinitos',
    prompt: '"Generador de Robux 2026 — ingresá tu usuario y duplicamos tu saldo".',
    context: 'Un video de YouTube con miles de vistas.',
    choices: [
      {
        id: 'enter_user',
        label: 'Ingresar tu usuario',
        outcomeQuality: 'dangerous',
        deltas: { security: -20, money: -25, stress: 15 },
        feedback: 'Te robaron la cuenta. Los generadores no existen.',
        teaches: 'online_scam',
        xpReward: 5,
      },
      {
        id: 'ignore',
        label: 'Ignorar y reportar el video',
        outcomeQuality: 'safe',
        deltas: { knowledge: 6, security: 4 },
        feedback: 'Cero tolerancia a lo "gratis" sin esfuerzo.',
        teaches: 'online_scam',
        xpReward: 25,
      },
      {
        id: 'teach',
        label: 'Comentar explicando que es una estafa',
        outcomeQuality: 'educational',
        deltas: { reputation: 10, knowledge: 10, stress: -3 },
        feedback: 'Educar a otros jugadores multiplica tu impacto.',
        teaches: 'online_scam',
        xpReward: 45,
      },
    ],
    minLevel: 2,
    tags: ['gratis', 'video', 'jóvenes'],
    modes: ['story', 'survival', 'school'],
  },
  {
    id: 'evt_gaming_vbucks',
    zoneId: 'gaming',
    category: 'phishing',
    title: 'V-Bucks "de regalo"',
    prompt: 'Un sitio promete 10.000 V-Bucks si iniciás sesión con tu cuenta de Epic.',
    context: 'El sitio tiene el logo oficial. La URL no.',
    choices: [
      {
        id: 'login',
        label: 'Iniciar sesión',
        outcomeQuality: 'dangerous',
        deltas: { security: -30, money: -20 },
        feedback: 'Login falso. Perdiste la cuenta.',
        teaches: 'phishing',
        xpReward: 5,
      },
      {
        id: 'check_url',
        label: 'Revisar la URL y cerrar',
        outcomeQuality: 'safe',
        deltas: { security: 8, knowledge: 10 },
        feedback: 'Una URL sospechosa es una trampa visible.',
        teaches: 'phishing',
        xpReward: 30,
      },
      {
        id: 'report',
        label: 'Reportar el sitio a Epic',
        outcomeQuality: 'educational',
        deltas: { security: 10, reputation: 8, knowledge: 8 },
        feedback: 'Tu reporte protege a miles de jugadores.',
        teaches: 'phishing',
        xpReward: 45,
      },
    ],
    minLevel: 2,
    tags: ['login', 'url', 'videojuego'],
    modes: ['story', 'survival'],
  },

  // ---------- NEWS ----------
  {
    id: 'evt_news_clickbait',
    zoneId: 'news',
    category: 'fake_news',
    title: 'El titular imposible',
    prompt:
      '"Científicos confirman que comer chocolate cura el COVID-19. Estudio completo adentro".',
    context: 'El sitio tiene un nombre similar a un medio real.',
    choices: [
      {
        id: 'share',
        label: 'Compartir sin verificar',
        outcomeQuality: 'dangerous',
        deltas: { reputation: -20, knowledge: -10, stress: 5 },
        feedback: 'Difundiste desinformación.',
        teaches: 'fake_news',
        xpReward: 5,
      },
      {
        id: 'verify',
        label: 'Buscar la fuente original del estudio',
        outcomeQuality: 'safe',
        deltas: { knowledge: 15, reputation: 5 },
        feedback: 'La verificación es tu superpoder.',
        teaches: 'fake_news',
        xpReward: 35,
      },
      {
        id: 'factcheck',
        label: 'Consultar un sitio de fact-checking',
        outcomeQuality: 'educational',
        deltas: { knowledge: 18, reputation: 10, security: 3 },
        feedback: 'Sitios como Maldito Bulo, Snopes o Chequeado son aliados.',
        teaches: 'fake_news',
        xpReward: 50,
      },
    ],
    minLevel: 3,
    tags: ['salud', 'clickbait', 'compartir'],
    modes: ['story', 'survival', 'school'],
  },
  {
    id: 'evt_news_echo',
    zoneId: 'news',
    category: 'disinformation',
    title: 'El eco de tu feed',
    prompt: 'Tu feed solo te muestra noticias que confirman lo que ya creés. ¿Qué hacés?',
    context: 'Estás en una burbuja de filtro.',
    choices: [
      {
        id: 'feed_more',
        label: 'Seguir consumiendo lo mismo',
        outcomeQuality: 'dangerous',
        deltas: { knowledge: -15, stress: 15, trust: -10 },
        feedback: 'El algoritmo te radicaliza pasivamente.',
        teaches: 'algorithmic_manipulation',
        xpReward: 5,
      },
      {
        id: 'diversify',
        label: 'Seguir medios con otras perspectivas',
        outcomeQuality: 'safe',
        deltas: { knowledge: 12, trust: 8 },
        feedback: 'Diversificar fuentes rompe cámaras de eco.',
        teaches: 'disinformation',
        xpReward: 30,
      },
      {
        id: 'reset',
        label: 'Limpiar el historial y reconfigurar intereses',
        outcomeQuality: 'educational',
        deltas: { knowledge: 15, stress: -10, security: 5 },
        feedback: 'Curar tu feed es higiene digital.',
        teaches: 'algorithmic_manipulation',
        xpReward: 45,
      },
    ],
    minLevel: 3,
    tags: ['algoritmo', 'feed', 'opinión'],
    modes: ['story', 'survival', 'school'],
  },

  // ---------- SHOPPING ----------
  {
    id: 'evt_shop_airpods',
    zoneId: 'shopping',
    category: 'online_scam',
    title: 'AirPods a u$s 19',
    prompt: 'Una tienda online ofrece AirPods Max al 95% de descuento. Stock limitado.',
    context: 'El sitio tiene reseñas falsas y dominio creado ayer.',
    choices: [
      {
        id: 'buy',
        label: 'Comprar 3 unidades',
        outcomeQuality: 'dangerous',
        deltas: { money: -40, security: -20, stress: 15 },
        feedback: 'Te llegaron réplicas truchas. Perdiste la plata y los datos.',
        teaches: 'online_scam',
        xpReward: 5,
      },
      {
        id: 'whois',
        label: 'Hacer un whois del dominio y comparar precios',
        outcomeQuality: 'safe',
        deltas: { knowledge: 12, security: 5 },
        feedback: 'Un dominio de ayer y precios únicos son banderas rojas.',
        teaches: 'online_scam',
        xpReward: 30,
      },
      {
        id: 'report',
        label: 'Reportar el sitio y avisar a tu banco',
        outcomeQuality: 'educational',
        deltas: { security: 12, reputation: 8, knowledge: 8 },
        feedback: 'Proteger a otros consumidores es clave.',
        teaches: 'online_scam',
        xpReward: 50,
      },
    ],
    minLevel: 4,
    tags: ['tienda', 'precio', 'tarjeta'],
    modes: ['story', 'survival', 'school'],
  },

  // ---------- AI ----------
  {
    id: 'evt_ai_deepfake_call',
    zoneId: 'ai',
    category: 'deepfake',
    title: 'La voz de tu mamá',
    prompt: 'Recibís una llamada: "Hola hijo, tuve un accidente. Necesito u$s 2000 ya".',
    context: 'La voz suena idéntica a la de tu madre.',
    speaker: { id: 'npc_abu', name: 'Abuela Rosa', avatar: '👵', archetype: 'grandma' },
    choices: [
      {
        id: 'transfer',
        label: 'Transferir sin verificar',
        outcomeQuality: 'dangerous',
        deltas: { money: -40, trust: -15, security: -10 },
        feedback: 'Voz clonada con IA. Estafa consumada.',
        teaches: 'deepfake',
        xpReward: 5,
      },
      {
        id: 'callback',
        label: 'Colgar y llamar al número conocido de tu mamá',
        outcomeQuality: 'safe',
        deltas: { security: 10, trust: 5, knowledge: 8 },
        feedback: 'Verificar por canal fuera de banda es regla de oro.',
        teaches: 'deepfake',
        xpReward: 35,
      },
      {
        id: 'report',
        label: 'Reportar a la policía y a la familia',
        outcomeQuality: 'educational',
        deltas: { security: 12, knowledge: 12, reputation: 8, stress: -5 },
        feedback: 'Tu familia te lo va a agradecer.',
        teaches: 'deepfake',
        xpReward: 50,
      },
    ],
    minLevel: 5,
    tags: ['voz', 'ia', 'urgencia'],
    modes: ['story', 'survival', 'school'],
  },
  {
    id: 'evt_ai_image',
    zoneId: 'ai',
    category: 'deceptive_ai',
    title: 'La foto que no ocurrió',
    prompt: 'Una cuenta comparte una "foto filtrada" de un político en una situación comprometida.',
    context: 'La imagen tiene marcas extrañas en los bordes.',
    choices: [
      {
        id: 'share',
        label: 'Compartir y comentar indignado',
        outcomeQuality: 'dangerous',
        deltas: { reputation: -20, knowledge: -10, stress: 5 },
        feedback: 'Era una imagen sintética. Alimentaste la difamación.',
        teaches: 'deceptive_ai',
        xpReward: 5,
      },
      {
        id: 'metadata',
        label: 'Revisar metadatos y buscar la fuente',
        outcomeQuality: 'safe',
        deltas: { knowledge: 12, security: 4 },
        feedback: 'Las imágenes sintéticas suelen dejar huellas.',
        teaches: 'deceptive_ai',
        xpReward: 30,
      },
      {
        id: 'reverse',
        label: 'Hacer búsqueda inversa y reportar',
        outcomeQuality: 'educational',
        deltas: { knowledge: 18, reputation: 10 },
        feedback: 'La búsqueda inversa es detective digital puro.',
        teaches: 'deceptive_ai',
        xpReward: 50,
      },
    ],
    minLevel: 5,
    tags: ['imagen', 'política', 'verificación'],
    modes: ['story', 'survival'],
  },

  // ---------- DARK NETWORK ----------
  {
    id: 'evt_dark_chain',
    zoneId: 'dark_network',
    category: 'grooming',
    title: 'El "amigo" desconocido',
    prompt: 'Un adulto te contacta por DM alabando tus fotos y pidiendo "privacidad".',
    context: 'Dice entenderte más que tus padres.',
    choices: [
      {
        id: 'engage',
        label: 'Seguir la conversación en privado',
        outcomeQuality: 'dangerous',
        deltas: { security: -25, trust: -25, stress: 20, knowledge: -5 },
        feedback: 'Esto es grooming. Cortar y denunciar salva vidas.',
        teaches: 'grooming',
        xpReward: 5,
      },
      {
        id: 'block',
        label: 'Bloquear y contarle a un adulto de confianza',
        outcomeQuality: 'safe',
        deltas: { security: 10, trust: 10, stress: -10 },
        feedback: 'Hablarlo con alguien de confianza es el camino.',
        teaches: 'grooming',
        xpReward: 40,
      },
      {
        id: 'report',
        label: 'Reportar a la plataforma y guardar pruebas',
        outcomeQuality: 'educational',
        deltas: { security: 15, knowledge: 12, reputation: 8 },
        feedback: 'Tu reporte puede proteger a otros jóvenes.',
        teaches: 'grooming',
        xpReward: 60,
      },
    ],
    minLevel: 7,
    tags: ['dm', 'menor', 'privacidad'],
    modes: ['story', 'school'],
  },
  {
    id: 'evt_dark_addiction',
    zoneId: 'dark_network',
    category: 'digital_addiction',
    title: 'La noche sin fin',
    prompt: 'Son las 3 AM. Estás en tu 5ta hora de scroll. Tenés examen mañana.',
    context: 'La app te ofrece exactamente el contenido que tu cerebro desea.',
    choices: [
      {
        id: 'keep_scrolling',
        label: 'Una más…',
        outcomeQuality: 'dangerous',
        deltas: { time: -20, stress: 20, knowledge: -10, security: 0 },
        feedback: 'El loop infinito de dopamina te ganó.',
        teaches: 'digital_addiction',
        xpReward: 5,
      },
      {
        id: 'sleep',
        label: 'Dejar el teléfono fuera de la habitación',
        outcomeQuality: 'safe',
        deltas: { time: 10, stress: -15, knowledge: 8 },
        feedback: 'Dormir es la habilidad más infravalorada.',
        teaches: 'digital_addiction',
        xpReward: 30,
      },
      {
        id: 'schedule',
        label: 'Configurar horarios y límites de pantalla',
        outcomeQuality: 'educational',
        deltas: { time: 15, stress: -10, knowledge: 10, security: 5 },
        feedback: 'Tus hábitos digitales son código que podés reescribir.',
        teaches: 'digital_addiction',
        xpReward: 50,
      },
    ],
    minLevel: 4,
    tags: ['scrroll', 'sueño', 'hábitos'],
    modes: ['story', 'survival', 'school'],
  },
];
